development:
  adapter: mysql
  encoding: utf8
  database: testchef_development
  username: root
  password: 
  host: localhost
  port: 3306

test:
  adapter: mysql
  encoding: utf8
  database: testchef_test
  username: root
  password:
  host: localhost
  port: 3306

